version: '2'

volumes:
  postgres_data:
      driver: local

networks:
  microservice:
    name: microservice-network
    external: true

services:
  postgres:
      image: postgres
      container_name: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      environment:
        POSTGRES_DB: $POSTGRES_DB_USER_MANAGEMENT_SVC
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      ports:
        -  5432:5432
      networks:
        - microservice